services:
  db:
    image: postgis/postgis:17-3.5
    shm_size: 1g
    restart: unless-stopped
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pg_data:/var/lib/postgresql

  nginx:
    image: nginx:1.27
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/etc/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
